packages:
  - packages/*
  - scripts

catalogs:
  cli:
    dprint: ^0.51.1
    lint-staged: ^16.2.7
    oxlint: ^1.36.0
    oxlint-tsgolint: ^0.10.0
    simple-git-hooks: ^2.13.1
    taze: ^19.9.2
    tsdown: ^0.18.3
    vitest: ^4.0.16
    changelogithub: ^14.0.0
    bumpp: ^10.3.2
  types:
    typescript: ^5.9.3
    '@types/node': ^25.0.3
    type-fest: ^5.3.1
  napi:
    '@napi-rs/cli': ^3.5.0
    '@napi-rs/wasm-runtime': ^1.1.0
  scripts:
    tsx: ^4.21.0
    '@iarna/toml': ^2.2.5

onlyBuiltDependencies:
  - dprint
  - esbuild
  - simple-git-hooks

verifyDepsBeforeRun: install
