packages:
  - packages/*

verifyDepsBeforeRun: install

catalogs:
  cli:
    dprint: ^0.50.2
    oxlint: ^1.28.0
    oxlint-tsgolint: ^0.6.0
    vitest: ^4.0.8
    taze: ^19.9.0
  types:
    typescript: ^5.9.3
